### ISSUE TITLE
Stops cycling after the first Fn press

### ISSUE THREAD

**Issue by whiplashoo** [Nikeev/LangSwitch#1]
Installed it and set the Fn button to "Do Nothing". I ran the app, and pressing it once properly changed the language immediately. However, subsequent presses don't work. 

![Screenshot 2023-09-04 at 9 41 03 AM](https://github.com/Nikeev/LangSwitch/assets/9117427/9290a0c7-e05b-4239-b9be-b46e44803277)

Running it via XCode, gives these logs:

```
Switched to: Greek
Switched to: Dictation
Switched to: Dictation
Switched to: Dictation
Switched to: Dictation
...
```

**Comment by whiplashoo** [comment]
Adding this:

```Swift
 if sourceName != "Dictation" && sourceName != "Emoji & Symbols" && sourceName != "com.apple.PressAndHold" {
    break
}
```

fixes the issue.

**Comment by Nikeev** [comment]
Thank you for your help! I'll update app later)

**Comment by Nikeev** [comment]
Fixed version uploaded, thanks!

**Comment by whiplashoo** [comment]
Great! Works like a charm
