### ISSUE TITLE
Layout switch working only once

### ISSUE THREAD

**Issue by dsazonoff** [Nikeev/LangSwitch#2]
Steps to reproduce:
1. Switch off standard action on Fn
2. Install and run app

Expected:
On Fn press language rotated.

Actual:
It is switched only to russian.
Log:
```
saz@SaZ-Macbook-Pro MacOS % ./LangSwitch
Switched to: Russian – PC
Switched to: EmojiFunctionRowIM_Extension
Switched to: EmojiFunctionRowIM_Extension
Switched to: EmojiFunctionRowIM_Extension
...
```

Environment:
MBP 2019, External magic keyboard with touch ID, latest MacOS

P.S. on MBP 2021 (M1 max) everything works fine.

**Comment by Nikeev** [comment]
Hello!

Thanks for the logs, I've added EmojiFunctionRowIM_Extension to exclude input sources list. 
Please check latest release, it should work now.

**Comment by dsazonoff** [comment]
Thanks a lot!
