### ISSUE TITLE
Hide Menu bar icon

### ISSUE THREAD

**Issue by lababiba1** [Nikeev/LangSwitch#9]
Hi, it would be great to have an opportunity to remove the Globe icon from the Menu bar. 
<img width="48" alt="image" src="https://github.com/Nikeev/LangSwitch/assets/54396355/1e63a8df-4275-4c66-975e-9cf411b47bf8">

**Comment by romanr** [comment]
Or if can hide macOS indicator then globe should show current locale. 
Also "Exit" menu without app name is not nice.

**Comment by romanr** [comment]
Take a look at which release, is it in release from two weeks ago?  😁

**Comment by Nikeev** [comment]
Yes, the latest) https://github.com/Nikeev/LangSwitch/releases/tag/v1.3.0
